# Autogenerated wrapper script for PORTA_jll for x86_64-w64-mingw32
export libporta, valid, xporta

JLLWrappers.@generate_wrapper_header("PORTA")
JLLWrappers.@declare_library_product(libporta, "libporta.dll")
JLLWrappers.@declare_executable_product(valid)
JLLWrappers.@declare_executable_product(xporta)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libporta,
        "bin\\libporta.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        valid,
        "bin\\valid.exe",
    )

    JLLWrappers.@init_executable_product(
        xporta,
        "bin\\xporta.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
